INSERT INTO types (name) VALUES ('Grass');
INSERT INTO types (name) VALUES ('Poison');
INSERT INTO types (name) VALUES ('Fire');
INSERT INTO types (name) VALUES ('Flying');
INSERT INTO types (name) VALUES ('Water');
INSERT INTO types (name) VALUES ('Bug');
INSERT INTO types (name) VALUES ('Normal');
INSERT INTO types (name) VALUES ('Electric');
INSERT INTO types (name) VALUES ('Ground');
INSERT INTO types (name) VALUES ('Fighting');
INSERT INTO types (name) VALUES ('Psychic');
INSERT INTO types (name) VALUES ('Rock');

INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (1, 1);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (1, 2);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (2, 1);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (2, 2);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (3, 1);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (3, 2);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (4, 3);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (5, 5);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (5, 9);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (5, 12);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (6, 3);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (6, 4);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (7, 1);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (7, 8);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (8, 5);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (9, 5);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (10, 6);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (11, 6);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (12, 4);
INSERT INTO pokemons_types (pokemon_id, type_id) VALUES (12, 6);
